### ISSUE TITLE
run method of Application having Configuration along with Environment.

### ISSUE THREAD

**Issue by ToOnlyGaurav** [flipkart-incubator/grpc-jexpress#12]
It will be really helpful if reading from yml and updating config is abstracted from client.
Currently, arguments are not available in the initialize method or run method so the client has to hard code .yml file name.
In Dropwizard this is abstracted from the client and has enforced to use yml format. In my opinion, we should do the same.

**Comment by regunathb** [comment]
Can the .yml file path not be supplied as start-up params to the Application, like we normally do for log4J configuration? Do you have an example for what you are proposing that you can share?
