### ISSUE TITLE
Dispatch-compose feature

### ISSUE THREAD

**Issue by pmohankumar** [flipkart-incubator/grpc-jexpress#6]
Capability wise, it would be similar to what [hydra](https://github.com/flipkart-incubator/hydra) provides but in a type-safe, less intrusive way.

Internal implementation would be opinionated on using hystrix for wrapping network calls.

**Comment by pmohankumar** [comment]
**Feature spec as suggested by @regunathb :**

Many of the micro services in SOA are seldom leaf service (i.e. the last in a call-graph) and would do some sort of Dispatch-Compose. For e.g. "Cart" service may call "Product" service to fetch product details for a given product id, call "Offer" service to fetch offers for those products, call "User" service to get user details and then its own persistence store. Similar to what we have in [Poseidon](https://github.com/flipkart-incubator/Poseidon) i.e [Hydra](https://github.com/flipkart-incubator/hydra), we could have something like:

public void foo(CartRequest req, StreamObserver<CartReply> responseObserver) {
     ProductResponse zr = callProduct(new ProductRequest(req.getProductId()));
     OfferResponse sr = callOffer(zr);
     UserResponse ur = callUser(new UserRequest(req.getUserId()));
     InterstitialResponse ir = callInterstitial(req);
     CartResponse cr = composeResponse(sr, ur, ir);
     responseObserver.onNext(cr);
     responseObserver.onCompleted();
}

@Task(Type=mandatory, Timeout=200, Retries=2)
public ProductResponse callProduct(ProductRequest req) {

}

@Task(Type=mandatory, Timeout=300, Retries=2)
public OfferResponse callOffer(ProductResponse req) {

}

@Task(Type=mandatory, Timeout=300, Retries=2)
public UserResponse callUser(UserRequest req) {

}

@Task(Type=mandatory, Timeout=300, Retries=2)
public CartResponse composeResponse(OfferReponse res, UserReponse res1, InterstitialResponse res2) {

}

@Task(Type=optional, Timeout=100, Fallback=getCachedInterstitial)
public InterstitialResponse callInterstitial(CartRequest req) {

}

@Task(Type=optional, Timeout=100)
public InterstitialResponse getCachedInterstitial(CartRequest req) {

}

In the above example, developer has indicated that what calls are mandatory and what are optional, timeouts for each and retries (we can be smart to execute these as well based on last 10 seconds 90th percentile numbers. See [Tail at scale](https://cacm.acm.org/magazines/2013/2/160173-the-tail-at-scale/fulltext). The developer has also indicated implicitly what calls are sequential and what can be concurrent - for e.g. calls to Offer has to happen after Product but Product and User calls can happen concurrently. We have implemented something very similar in [Flux](https://github.com/flipkart-incubator/Flux) and it works. Also, the developer can specify fallback in case of timeouts/errors - see the Fallback annotation property.
In the implementation, we could use libraries like Hydra, [Hystrix](https://github.com/Netflix/Hystrix) etc to achieve the behaviour.

IMO these will be pretty useful primitives to support in GJEX. What say?

**Comment by regunathb** [comment]
Post a discussion with Yogesh Nachnani, I would like to propose a different Dispatch-Compose implementation using CompletableFuture like below:

public void foo(CartRequest req) {
  /* callZulu returns a CompletableFuture */
  SantaResponseFuture sr = 
    callZulu(new ZuluRequest())
     .thenApply(
        SantaResponseFuture sr = callSanta(this)
      )
  UserResponseFuture ur = callUser();
  InterstitialResponse ir = callInterstitial();
  val finalResponse = CompletableFuture.allOf(sr, ur, ir).get()
}

This was Yogesh's suggestion and I think this is more clean and explicit on what is concurrent and what executes serially. I have done some ground work in providing the ability to annotate methods like @ConcurrentTask(timeout = 100) which is then executed as a HystrixCommand returning a Future. Now, next step is to convert this to CompletableFuture and enable composition.

**Comment by regunathb** [comment]
First version of implementation is committed to master. See : https://github.com/flipkart-incubator/grpc-jexpress/wiki/Concurrent-execution,-Dispatch-Compose

**Comment by regunathb** [comment]
Modified the implementation to use a custom FutureDecorator API instead of CompletableFuture to support Mandatory and Optional ConcurrentTask executions.
